"""initial_schema

Revision ID: 3214403b9d00
Revises: 
Create Date: 2026-03-20 00:36:26.326099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3214403b9d00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('reach', sa.Float(), nullable=True),
    sa.Column('stance', sa.String(length=50), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('weight_class', sa.String(length=100), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fighters_name', 'fighters', ['name'], unique=False)
    op.create_index('ix_fighters_weight_class', 'fighters', ['weight_class'], unique=False)
    op.create_table('fights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event', sa.String(length=255), nullable=True),
    sa.Column('fighter_a_id', sa.Integer(), nullable=False),
    sa.Column('fighter_b_id', sa.Integer(), nullable=False),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=100), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['fighter_a_id'], ['fighters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['fighter_b_id'], ['fighters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['winner_id'], ['fighters.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fights_date', 'fights', ['date'], unique=False)
    op.create_index('ix_fights_fighter_a_id', 'fights', ['fighter_a_id'], unique=False)
    op.create_index('ix_fights_fighter_b_id', 'fights', ['fighter_b_id'], unique=False)
    op.create_table('fight_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('knockdowns', sa.Integer(), nullable=True),
    sa.Column('significant_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('significant_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('total_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('total_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('head_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('head_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('body_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('body_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('takedowns_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_attempted', sa.Integer(), nullable=True),
    sa.Column('submission_attempts', sa.Integer(), nullable=True),
    sa.Column('reversals', sa.Integer(), nullable=True),
    sa.Column('control_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fight_stats_fight_id', 'fight_stats', ['fight_id'], unique=False)
    op.create_index('ix_fight_stats_fighter_id', 'fight_stats', ['fighter_id'], unique=False)
    op.create_table('historical_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('fighter_a_odds', sa.Integer(), nullable=True),
    sa.Column('fighter_b_odds', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_historical_odds_fight_id', 'historical_odds', ['fight_id'], unique=False)
    op.create_table('round_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('knockdowns', sa.Integer(), nullable=True),
    sa.Column('significant_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('significant_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('total_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('total_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('head_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('head_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('body_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('body_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('takedowns_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_attempted', sa.Integer(), nullable=True),
    sa.Column('submission_attempts', sa.Integer(), nullable=True),
    sa.Column('reversals', sa.Integer(), nullable=True),
    sa.Column('control_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fight_id'], ['fights.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fighter_id'], ['fighters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_round_stats_fight_id', 'round_stats', ['fight_id'], unique=False)
    op.create_index('ix_round_stats_fighter_id', 'round_stats', ['fighter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_round_stats_fighter_id', table_name='round_stats')
    op.drop_index('ix_round_stats_fight_id', table_name='round_stats')
    op.drop_table('round_stats')
    op.drop_index('ix_historical_odds_fight_id', table_name='historical_odds')
    op.drop_table('historical_odds')
    op.drop_index('ix_fight_stats_fighter_id', table_name='fight_stats')
    op.drop_index('ix_fight_stats_fight_id', table_name='fight_stats')
    op.drop_table('fight_stats')
    op.drop_index('ix_fights_fighter_b_id', table_name='fights')
    op.drop_index('ix_fights_fighter_a_id', table_name='fights')
    op.drop_index('ix_fights_date', table_name='fights')
    op.drop_table('fights')
    op.drop_index('ix_fighters_weight_class', table_name='fighters')
    op.drop_index('ix_fighters_name', table_name='fighters')
    op.drop_table('fighters')
    # ### end Alembic commands ###
